# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4357ffb553150034979ec94e0e6c606de06d3305bf59f639807f1c48c1ca03dcd4ff48aaa6e3d7d0aa46ab5ef156fea4e7873443f98696c09d8fcdf4d4f2aa0f

test:
  secret_key_base: bc0c35949540316ec9f7c491c4b171f1c0f8d4c5f2431899edc20b893a3ee6017314eef10611df8096506d7a9829a8a145f1487a96a80857cfb9baadeac7b5c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
